#!/bin/bash
# (C) 2005 Jörg Schirottke <master@kanotix.com>
# (C) 2006-2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>

usage () {
cat <<EOT
HWSETUP NG - bash emulation of former hwsetup for combined usage with udev
(C) 2005 Joerg Schirottke <master@kanotix.com>
(C) 2006-2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
Usage: $(basename $0) [options]
 
available options:
 
	-v	verbose mode
	-n	debug mode (always verbose)
EOT
}

# combine output
echo_var () {
	[ "${!1}" ] && echo "$1=\"${!1}\""
}

PATH="/usr/share/hwsetup-ng:$PATH"

unset VERBOSE DEBUG
while (($#)); do
	case $1 in
 		-v)	VERBOSE=1
			;;
		-n)	DEBUG=1
			;;
		*)	usage
			exit 1
	esac
	shift
done

HWSETUP_MAIN="/etc/hwsetup"

[ "$DEBUG" ] || (
	rm -f "$HWSETUP_MAIN"
)

# xserver detection - external script
if [ "$DEBUG" ]; then
	hwsetup-xserver
else
	hwsetup-xserver > "$HWSETUP_MAIN"
	. "$HWSETUP_MAIN"
fi

# mouse detection - serial mouse via hwinfo (SuSE)
unset SERIAL PS2 USB MOUSE_DEVICE MOUSE_FULLNAME

if [ -x /usr/sbin/hwinfo ]; then
	SERIAL=$(/usr/sbin/hwinfo --mouse --short | grep /dev/tty | head -1)
fi

if [ "$SERIAL" ]; then
	MOUSE_MOUSETYPE="ms"
	MOUSE_XMOUSETYPE="Microsoft"
	MOUSE_FULLNAME="$(echo $SERIAL|cut -d' ' -f2-)"
	MOUSE_DEVICE="$(echo $SERIAL|cut -d' ' -f1)"
fi

PS2="$(grep -v ^S: /proc/bus/input/devices|grep Handlers=mouse -B2|grep Phys=isa -B1|tail -2|head -1|perl -pe '($_)=/Name="(.*)"/')"
if [ "$PS2" -a ! "$SERIAL" ]; then
	MOUSE_MOUSETYPE="ps2"
	MOUSE_XMOUSETYPE="PS/2"
	MOUSE_FULLNAME="$PS2"
	MOUSE_DEVICE="/dev/psaux"
fi

USB="$(grep -v ^S: /proc/bus/input/devices|grep Handlers=mouse -B2|grep Phys=usb -B1|tail -2|head -1|perl -pe '($_)=/Name="(.*)"/')"
[ ! "$USB" ] && USB="$(grep -v ^S: /proc/bus/input/devices|grep Handlers=.*mouse -B2|grep Phys=usb -B1|tail -2|head -1|perl -pe '($_)=/Name="(.*)"/')"

if [ "$USB" -a ! "$PS2" -a ! "$SERIAL" ]; then
	MOUSE_MOUSETYPE="imps2"
	MOUSE_XMOUSETYPE="IMPS/2"
	MOUSE_FULLNAME="$USB"
	MOUSE_DEVICE="/dev/input/mice"
fi

[ "$DEBUG" ] || (
	echo_var MOUSE_FULLNAME
	echo_var MOUSE_DEVICE
	echo_var MOUSE_MOUSETYPE
	echo_var MOUSE_XMOUSETYPE
	echo_var XSERVER
	echo_var XMODULE
	echo_var XDESC
) > "$HWSETUP_MAIN"

[ "$VERBOSE" -a ! "$DEBUG" ] && (
	echo_var MOUSE_MOUSETYPE
	echo_var MOUSE_XMOUSETYPE
	echo_var MOUSE_FULLNAME
	echo_var MOUSE_DEVICE
	echo_var XSERVER
	echo_var XMODULE
	echo_var XDESC
)

[ "$DEBUG" ] && (
	echo_var MOUSE_MOUSETYPE
	echo_var MOUSE_XMOUSETYPE
	echo_var MOUSE_FULLNAME
	echo_var MOUSE_DEVICE
)

exit 0

